### ISSUE TITLE
VITE_API_SERVICESTATUS_URL Issue

### ISSUE THREAD

**Issue by limi-mathew** [AlpayC/AlpayC#1]
I am working on Portfolio that you uploaded in git Bit I need the VITE_API_SERVICESTATUS_URL value in env ,May I know what is the Url for getting the service status?

**Comment by AlpayC** [comment]
Hi, of course you can. It's a uptime service like uptime Kuma. It's totally free and I highly recommend it. 

Here your can generate your own status pages  and your own link with the referenced api key
[BetterUptime](https://betterstack.com/)
